server:
  port: 8761

spring:
  application:
    name: autoinsy-eureke
  freemarker:
    prefer-file-system-access: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: false